# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_files\start.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 545)
        MainWindow.setStyleSheet("QWidget {\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0064ff; \n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    border: 2px solid blue;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0000ff;\n"
"}\n"
"\n"
"QSpinBox, QComboBox {\n"
"    padding: 3px;\n"
"    border-radius: 4px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.searchPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchPushButton.setObjectName("searchPushButton")
        self.gridLayout.addWidget(self.searchPushButton, 9, 2, 1, 1)
        self.searchLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.gridLayout.addWidget(self.searchLineEdit, 9, 1, 1, 1)
        self.dataTable = QtWidgets.QTableWidget(self.centralwidget)
        self.dataTable.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.dataTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(0)
        self.dataTable.setRowCount(0)
        self.gridLayout.addWidget(self.dataTable, 8, 0, 1, 3)
        self.qHorizontalLayout = QtWidgets.QHBoxLayout()
        self.qHorizontalLayout.setObjectName("qHorizontalLayout")
        self.quantityLabel = QtWidgets.QLabel(self.centralwidget)
        self.quantityLabel.setObjectName("quantityLabel")
        self.qHorizontalLayout.addWidget(self.quantityLabel)
        self.quantitySpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.quantitySpinBox.setMinimum(1)
        self.quantitySpinBox.setMaximum(10000)
        self.quantitySpinBox.setObjectName("quantitySpinBox")
        self.qHorizontalLayout.addWidget(self.quantitySpinBox)
        self.columnsLabel = QtWidgets.QLabel(self.centralwidget)
        self.columnsLabel.setObjectName("columnsLabel")
        self.qHorizontalLayout.addWidget(self.columnsLabel)
        self.columnsSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.columnsSpinBox.setMinimum(1)
        self.columnsSpinBox.setMaximum(1000)
        self.columnsSpinBox.setObjectName("columnsSpinBox")
        self.qHorizontalLayout.addWidget(self.columnsSpinBox)
        self.gridLayout.addLayout(self.qHorizontalLayout, 5, 0, 1, 3)
        self.actionsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.actionsHorizontalLayout.setObjectName("actionsHorizontalLayout")
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setMouseTracking(False)
        self.generateButton.setObjectName("generateButton")
        self.actionsHorizontalLayout.addWidget(self.generateButton)
        self.applyButton = QtWidgets.QPushButton(self.centralwidget)
        self.applyButton.setObjectName("applyButton")
        self.actionsHorizontalLayout.addWidget(self.applyButton)
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setObjectName("resetButton")
        self.actionsHorizontalLayout.addWidget(self.resetButton)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.actionsHorizontalLayout.addWidget(self.saveButton)
        self.showButton = QtWidgets.QPushButton(self.centralwidget)
        self.showButton.setObjectName("showButton")
        self.actionsHorizontalLayout.addWidget(self.showButton)
        self.gridLayout.addLayout(self.actionsHorizontalLayout, 6, 0, 1, 3)
        self.configHorizontalLayout = QtWidgets.QHBoxLayout()
        self.configHorizontalLayout.setObjectName("configHorizontalLayout")
        self.saveConfigButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveConfigButton.setObjectName("saveConfigButton")
        self.configHorizontalLayout.addWidget(self.saveConfigButton)
        self.loadConfigButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadConfigButton.setObjectName("loadConfigButton")
        self.configHorizontalLayout.addWidget(self.loadConfigButton)
        self.gridLayout.addLayout(self.configHorizontalLayout, 9, 0, 1, 1)
        self.minHorizontalLayout = QtWidgets.QHBoxLayout()
        self.minHorizontalLayout.setObjectName("minHorizontalLayout")
        self.minLabel = QtWidgets.QLabel(self.centralwidget)
        self.minLabel.setObjectName("minLabel")
        self.minHorizontalLayout.addWidget(self.minLabel)
        self.minSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.minSpinBox.setMinimum(-1000000)
        self.minSpinBox.setMaximum(1000000)
        self.minSpinBox.setObjectName("minSpinBox")
        self.minHorizontalLayout.addWidget(self.minSpinBox)
        self.gridLayout.addLayout(self.minHorizontalLayout, 1, 0, 1, 1)
        self.maxHorizontalLayout = QtWidgets.QHBoxLayout()
        self.maxHorizontalLayout.setObjectName("maxHorizontalLayout")
        self.maxLabel = QtWidgets.QLabel(self.centralwidget)
        self.maxLabel.setObjectName("maxLabel")
        self.maxHorizontalLayout.addWidget(self.maxLabel)
        self.maxSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.maxSpinBox.setMinimum(-1000000)
        self.maxSpinBox.setMaximum(1000000)
        self.maxSpinBox.setObjectName("maxSpinBox")
        self.maxHorizontalLayout.addWidget(self.maxSpinBox)
        self.gridLayout.addLayout(self.maxHorizontalLayout, 2, 0, 1, 1)
        self.typeHorizontalLayout = QtWidgets.QHBoxLayout()
        self.typeHorizontalLayout.setObjectName("typeHorizontalLayout")
        self.dataTypeComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.dataTypeComboBox.setObjectName("dataTypeComboBox")
        self.dataTypeComboBox.addItem("")
        self.dataTypeComboBox.addItem("")
        self.typeHorizontalLayout.addWidget(self.dataTypeComboBox)
        self.precisionSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.precisionSpinBox.setMaximum(6)
        self.precisionSpinBox.setObjectName("precisionSpinBox")
        self.typeHorizontalLayout.addWidget(self.precisionSpinBox)
        self.gridLayout.addLayout(self.typeHorizontalLayout, 1, 2, 1, 1)
        self.distributionHorizontalLayout = QtWidgets.QHBoxLayout()
        self.distributionHorizontalLayout.setObjectName("distributionHorizontalLayout")
        self.ditributionLabel = QtWidgets.QLabel(self.centralwidget)
        self.ditributionLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ditributionLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ditributionLabel.setObjectName("ditributionLabel")
        self.distributionHorizontalLayout.addWidget(self.ditributionLabel)
        self.distributionComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.distributionComboBox.setObjectName("distributionComboBox")
        self.distributionComboBox.addItem("")
        self.distributionComboBox.addItem("")
        self.distributionComboBox.addItem("")
        self.distributionHorizontalLayout.addWidget(self.distributionComboBox)
        self.gridLayout.addLayout(self.distributionHorizontalLayout, 2, 2, 1, 1)
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchPushButton.setText(_translate("MainWindow", "search"))
        self.quantityLabel.setText(_translate("MainWindow", "quantity of samples:"))
        self.columnsLabel.setText(_translate("MainWindow", "total columns:"))
        self.generateButton.setText(_translate("MainWindow", "generate"))
        self.applyButton.setText(_translate("MainWindow", "apply"))
        self.resetButton.setText(_translate("MainWindow", "reset"))
        self.saveButton.setText(_translate("MainWindow", "save to CSV"))
        self.showButton.setText(_translate("MainWindow", "show graph"))
        self.saveConfigButton.setText(_translate("MainWindow", "save config"))
        self.loadConfigButton.setText(_translate("MainWindow", "load config"))
        self.minLabel.setText(_translate("MainWindow", "min value:"))
        self.maxLabel.setText(_translate("MainWindow", "max value:"))
        self.dataTypeComboBox.setItemText(0, _translate("MainWindow", "float"))
        self.dataTypeComboBox.setItemText(1, _translate("MainWindow", "integer"))
        self.ditributionLabel.setText(_translate("MainWindow", "distribution:"))
        self.distributionComboBox.setItemText(0, _translate("MainWindow", "uniform"))
        self.distributionComboBox.setItemText(1, _translate("MainWindow", "normal"))
        self.distributionComboBox.setItemText(2, _translate("MainWindow", "exponential"))
        self.title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">NumHeaven</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
